// MARK: - Database Migrations

/**
 * Migration SQL generated by Drizzle Kit
 * Run `npx drizzle-kit generate` to regenerate after schema changes
 */
export const MIGRATION_0000 = `
CREATE TABLE IF NOT EXISTS approval_actions (
	id text PRIMARY KEY NOT NULL,
	action_type text NOT NULL,
	target_term_id text,
	status text DEFAULT 'pending' NOT NULL,
	created_at text NOT NULL,
	updated_at text
);

CREATE TABLE IF NOT EXISTS terms (
	term_id text PRIMARY KEY NOT NULL,
	term text NOT NULL,
	aliases text,
	context text,
	tags text,
	created_at text NOT NULL,
	updated_at text
);
`;

export const MIGRATION_0001 = `
CREATE TABLE IF NOT EXISTS settings (
	key text PRIMARY KEY NOT NULL,
	value text,
	updated_at text
);
`;

export const MIGRATION_0002 = `
ALTER TABLE approval_actions ADD term_details text;
`;

export const MIGRATION_0003 = `
ALTER TABLE terms ADD definition text;
ALTER TABLE terms ADD knowledge_triples text;
ALTER TABLE terms ADD last_synced_at text;
`;

export const ALL_MIGRATIONS = [MIGRATION_0000, MIGRATION_0001, MIGRATION_0002, MIGRATION_0003];
